language: java

cache:
  directories:
    - "$HOME/.m2"

notifications:
  email:
    recipients:
      - charles.prudhomme@imt-atlantique.fr
    on_success: always
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/26147fbe9b86b606f67d
    on_success: always
    on_failure: always
    on_start: never

env:
  global:
    # OSS SONATYPE, CI_DEPLOY_USERNAME=...
    - secure: hGeJ+dPc3AI/lOLIuVPuuo1LRrm432NXTsybYvlxIiRUpTDezHLWp/8okg+e+xF93jQSwzrTV0xBuH6upnixzzRzo/6fepT6OINe6a/W/VyQL7vUqOvypHWahU7a85sypEMZ7xSKohrixIIxx+NHjD61Q1s5kSc/r+yGkbU2pzI=
    # OSS SONATYPE, CI_DEPLOY_PASSWORD=...
    - secure: bcwHH/i43WCwnHb6C3G3hNgcS/OOVgCVxoXSUPtsYWcLZxb4cV05vUzs5VO/Iiw/YBRHEQM342yCKS46wunqv2wwEXpzWRTJG0Pwpn2tEj4fjp0OzPsiTx9AWYSkbiQjHoIGWC57LgxNzpuqHJsi4xnc9iiwQaV6mdlJP3Ofb7E=
    # COVERITY_PROJECT_TOKEN=
    - secure: mGSoZXHuppx4dFkpUZkv/0q46/Rh5wleKrqchXpBSEKaWcYEl0FhGCAZz+yCgoqnbu/oqZ5mdwtOdqrBNIdzKfpXSjvReHJijGTMUNHpn1j06nYY+ar5OFDBZcmublf7S93aG0LzxLzqvDvmUKxBiOsFgKr3A/NPJwhB21dYDSE=

branches:
  only:
    - master
    - modules
jobs:
  include:
    - before_install: curl https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.0/codacy-coverage-reporter-6.0.0-assembly.jar -o codacy-coverage-reporter-assembly.jar
    - name: ibex
      jdk: openjdk8
      before_install: "/bin/sh ./.travis/install-ibex.sh"
      before_script:
        - mvn validate -Dibex.path=${TRAVIS_BUILD_DIR}/ibex/plugins/java
        - export LD_LIBRARY_PATH=/usr/local/lib
      env: TEST_SUITE="ibex"
    - name: 1s
      jdk: openjdk11
      env: TEST_SUITE="1s"
    - name: 10s
      jdk: openjdk11
      env: TEST_SUITE="10s"
    - name: checker
      jdk: openjdk11
      env: TEST_SUITE="checker"

script:
  - mvn clean install -DtestFailureIgnore=true -Dgroups=$TEST_SUITE

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

before_deploy:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust

deploy:
  - provider: script
    script: "/bin/sh ./.travis/deploy.sh"
    cleanup: false
    on:
      repo: chocoteam/choco-solver
      branch: master
      jdk: oraclejdk8
      condition: "$GROUP = 10s"
  - provider: script
    script: "/bin/sh ./.travis/deploy.sh"
    cleanup: false
    on:
      repo: chocoteam/choco-solver
      tags: true
      jdk: oraclejdk8
      condition: "$GROUP = 10s"
