os: linux
language: java
jdk: openjdk11

cache:
  directories:
    - "$HOME/.m2"

notifications:
  email:
    recipients:
      - charles.prudhomme@imt-atlantique.fr
    on_success: always
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/26147fbe9b86b606f67d
    on_success: always
    on_failure: always
    on_start: never

env:
  global:
    # OSS SONATYPE, CI_DEPLOY_USERNAME=...
    - secure: hGeJ+dPc3AI/lOLIuVPuuo1LRrm432NXTsybYvlxIiRUpTDezHLWp/8okg+e+xF93jQSwzrTV0xBuH6upnixzzRzo/6fepT6OINe6a/W/VyQL7vUqOvypHWahU7a85sypEMZ7xSKohrixIIxx+NHjD61Q1s5kSc/r+yGkbU2pzI=
    # OSS SONATYPE, CI_DEPLOY_PASSWORD=...
    - secure: bcwHH/i43WCwnHb6C3G3hNgcS/OOVgCVxoXSUPtsYWcLZxb4cV05vUzs5VO/Iiw/YBRHEQM342yCKS46wunqv2wwEXpzWRTJG0Pwpn2tEj4fjp0OzPsiTx9AWYSkbiQjHoIGWC57LgxNzpuqHJsi4xnc9iiwQaV6mdlJP3Ofb7E=
    # COVERITY_PROJECT_TOKEN=
    - secure: mGSoZXHuppx4dFkpUZkv/0q46/Rh5wleKrqchXpBSEKaWcYEl0FhGCAZz+yCgoqnbu/oqZ5mdwtOdqrBNIdzKfpXSjvReHJijGTMUNHpn1j06nYY+ar5OFDBZcmublf7S93aG0LzxLzqvDvmUKxBiOsFgKr3A/NPJwhB21dYDSE=

branches:
  only:
    - master
    - modules

before_install:
  - /bin/bash ./.travis/before_install.sh
  - curl https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.0/codacy-coverage-reporter-6.0.0-assembly.jar -o codacy-coverage-reporter-assembly.jar
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
before_deploy:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust

jobs:
  include:
    # first run all tests
    - stage: test
      script: echo "ibex" #mvn clean install -DtestFailureIgnore=true -Dgroups="ibex"
      name: "ibex"
    - script: echo "1s" #mvn clean install -DtestFailureIgnore=true -Dgroups="1s"
      name: "1s"
    - script: echo "10s" #mvn clean install -DtestFailureIgnore=true -Dgroups="10s"
      name: "10s"
    - script: echo "checker" #mvn clean install -DtestFailureIgnore=true -Dgroups="checker"
      name: "checker"
    # then deploy
    - stage: deploy
      script: skip
      deploy:
        - provider: script
          script: /bin/bash ./.travis/deploy.sh
          cleanup: false
          on:
            branch: master
        - provider: releases
          api_key:
            secure: ZHDK6ygs4i0rinp0mQHD7nfwct/G1OqmJXrmbAht92TCfa36ffqqD4KFh/+FLO/hXd/PFxsIGVRwcVPtKxaKJ7+cO4jN9iXP4gGDQts83jwsJ/wbgajVfoHjLOJq2+YR+Ai1e21yyqrqZMDX84eW3UFO2BXwqFMPpiQIg/N8YII=
          cleanup: false
          #file: todo
          on:
            tags: true
            branch: master
