language: java
sudo: false
os:
  - linux
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
env:
  global:
  - secure: hb7XCxuEw3VDF5goORctgcFDwg2Z/WAz1ZHKWNRZmR+M1nN6rgDmwOaJpxepLlU0r/Ku14xspE0yn0nK3P1DFNptXhruDJ1h0+mcwiHdsHOM/Vdo247pPbI9pJTD6gQpNnlgVXAI0s5lkNf3IY2jszzhapKFEMHvnPMFXw/sVzU=
  - secure: LQcrlV3dVHoI2gKGOcDUdLzk32L83SuIK7mN3zNoaWmIh60Q5G1LLsoeEuR0VueY22aNnoOGTI0KmQsTD4JlpebjxWMYpH9SdHTCsge60/fhcv2GhuJwBVD70+Vex7lOKbpuFRQM+JWuyHh8EjWBkjTNYWae1XGzUYBhaJBpgJQ=
   # COVERITY_SCAN_TOKEN
  - secure: SOqRgXwXEaxXYP+zY1C7qIhm09n1Cds4c1yc9TPzokftl8pZKZIbY0bkNl4/HAbDgX0pibrja6nxQ9A1BOuAiCB3mSK7qBPxccq6tvFBhuy2IMxIYFw0tFuP3Cr+NULeYERlLs8wG0oayR8NbdQfYZgFh5+Jzzna133C+X+c/pE=
  matrix:
  - GROUP=1s
  - GROUP=10s
branches:
  only:
  - develop
  - master
  - /^feature.*$/
notifications:
  email:
    recipients:
    - choco@emn.fr
    on_success: change
    on_failure: always
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/26147fbe9b86b606f67d
    on_success: change
    on_failure: always
    on_start: never
script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mvn clean install -DtestFailureIgnore=true -Dgroups=$GROUP ; fi
addons:
  coverity_scan:
    project:
      name: "chocoteam/choco-solver"
      description: "Build submitted via Travis CI"
    notification_email: choco@emn.fr
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - curl http://testr-1154.appspot.com/assets/testR.py | python
