language: java
sudo: false
jdk:
- oraclejdk8
before_install:
  - pip install --user codecov
before_script:
  - export MAVEN_OPTS="-Xmx4096m -Xms128m -Xss64m -server"
env:
  - GROUP=1s
  - GROUP=10s
#  - GROUP=1m
#  - GROUP="correctness.*"
#  - GROUP="consistency.*"
script: travis_wait mvn clean install -DtestFailureIgnore=true -Dgroups=$GROUP
branches:
  only:
    - develop
    - master
    - /^feature.*$/

notifications:
  email:
    recipients:
      - choco@emn.fr
    on_success: always
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/26147fbe9b86b606f67d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

after_success:
  - codecov